# Loading Data

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../Data/insurance')
df.head()

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category
0,67,119.8,1.56,2.92,False,Jaipur,retired,High
1,36,101.1,1.83,34.28,False,Chennai,freelancer,Low
2,39,56.8,1.64,36.64,False,Indore,freelancer,Low
3,22,109.4,1.55,3.34,True,Mumbai,student,Medium
4,69,62.2,1.60,3.94,True,Indore,retired,High

In [3]:
df_copy = df.copy()
df_copy.head()

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category
0,67,119.8,1.56,2.92,False,Jaipur,retired,High
1,36,101.1,1.83,34.28,False,Chennai,freelancer,Low
2,39,56.8,1.64,36.64,False,Indore,freelancer,Low
3,22,109.4,1.55,3.34,True,Mumbai,student,Medium
4,69,62.2,1.60,3.94,True,Indore,retired,High

# Feature Engineering

In [4]:
df_copy['bmi'] = df_copy['weight'] / (df_copy['height']**2)
df_copy.head()

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category,bmi
0,67,119.8,1.56,2.92,False,Jaipur,retired,High,49.227482
1,36,101.1,1.83,34.28,False,Chennai,freelancer,Low,30.189017
2,39,56.8,1.64,36.64,False,Indore,freelancer,Low,21.118382
3,22,109.4,1.55,3.34,True,Mumbai,student,Medium,45.535900
4,69,62.2,1.60,3.94,True,Indore,retired,High,24.296875

In [5]:
def age_group(age):
    if age<25:
        return "young"
    elif age<45:
        return "adult"
    elif age<60:
        return "middleaged"
    else:
        return "senior"

In [6]:
df_copy['age_group'] = df_copy['age'].apply(age_group)
df_copy.head()

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category,bmi,age_group
0,67,119.8,1.56,2.92,False,Jaipur,retired,High,49.227482,senior
1,36,101.1,1.83,34.28,False,Chennai,freelancer,Low,30.189017,adult
2,39,56.8,1.64,36.64,False,Indore,freelancer,Low,21.118382,adult
3,22,109.4,1.55,3.34,True,Mumbai,student,Medium,45.535900,young
4,69,62.2,1.60,3.94,True,Indore,retired,High,24.296875,senior

In [7]:
def lifestyle_risk(row):
    if row['smoker'] and row['bmi'] > 30:
        return "high"
    elif row['smoker'] and row['bmi'] >25:
        return "medium"
    else:
        return "low"

In [8]:
df_copy["lifestyle_risk"] = df_copy.apply(lifestyle_risk, axis=1)

In [9]:
tier_1_cities = ["Mumbai", "Delhi", "Bangalore", "Chennai", "Kolkata", "Hyderabad", "Pune"]
tier_2_cities = [
    "Jaipur", "Chandigarh", "Indore", "Lucknow", "Patna", "Ranchi", "Visakhapatnam", "Coimbatore",
    "Bhopal", "Nagpur", "Vadodara", "Surat", "Rajkot", "Jodhpur", "Raipur", "Amritsar", "Varanasi",
    "Agra", "Dehradun", "Mysore", "Jabalpur", "Guwahati", "Thiruvananthapuram", "Ludhiana", "Nashik",
    "Allahabad", "Udaipur", "Aurangabad", "Hubli", "Belgaum", "Salem", "Vijayawada", "Tiruchirappalli",
    "Bhavnagar", "Gwalior", "Dhanbad", "Bareilly", "Aligarh", "Gaya", "Kozhikode", "Warangal",
    "Kolhapur", "Bilaspur", "Jalandhar", "Noida", "Guntur", "Asansol", "Siliguri"
]

In [10]:
def city_tier(city):
    if city in tier_1_cities:
        return 1
    elif city in tier_2_cities:
        return 2
    else:
        return 3

In [11]:
df_copy['city_tier'] = df_copy['city'].apply(city_tier)

In [12]:
df_copy.drop(columns=['age', 'weight', 
                    'height', 'smoker', 'city'])[['income_lpa',
                    'occupation', 'bmi', 'age_group', 'lifestyle_risk',
                    'city_tier', 'insurance_premium_category']].sample(5)

,income_lpa,occupation,bmi,age_group,lifestyle_risk,city_tier,insurance_premium_category
56,2.86,student,42.414152,young,high,1,Medium
77,0.61,retired,37.818734,senior,high,1,High
67,2.76,student,17.026929,young,low,2,Low
30,32.97,business_owner,29.937519,adult,low,1,Low
2,36.64,freelancer,21.118382,adult,low,2,Low

In [22]:
X_processed = df_copy[['income_lpa',
                    'occupation', 'bmi', 'age_group', 'lifestyle_risk',
                    'city_tier', 'insurance_premium_category']]

processed = pd.DataFrame(X_processed, columns=['income_lpa',
                    'occupation', 'bmi', 'age_group', 'lifestyle_risk',
                    'city_tier', 'insurance_premium_category'])
processed.to_csv('../Data/processed.csv', index=False)
processed.head(5)

,income_lpa,occupation,bmi,age_group,lifestyle_risk,city_tier,insurance_premium_category
0,2.92,retired,49.227482,senior,low,2,High
1,34.28,freelancer,30.189017,adult,low,1,Low
2,36.64,freelancer,21.118382,adult,low,2,Low
3,3.34,student,45.535900,young,high,1,Medium
4,3.94,retired,24.296875,senior,low,2,High